### ISSUE TITLE
Flux obsolète 

### ISSUE THREAD

**Issue by Emaison** [Mael-Le-Garrec/opencarbumap#9]
Bonjour, 
Le site officiel https://www.prix-carburants.gouv.fr/ utilise un flux "v2" qui est semble être plus à jour que celui que vous utilisez sur votre démo. Le nouveau est mis à jour toutes les 10 min et intègre d'après ce que j'ai compris les pénuries.
https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/information/

Comment faire pour le mettre à jour ?
D'avance, merci.

**Comment by Mael-Le-Garrec** [comment]
Salut,

A priori cette API n'est qu'une nouvelle mise en forme des données déjà existantes. Les données utilisées actuellement incluent déjà les carburants non disponibles.
Y a-t-il vraiment une utilité à utiliser cette API ?
La démo est mise à jour toutes les heures, c'est peut-être pour ça qu'on peut voir une différence.

A+

**Comment by Emaison** [comment]
Merci pour ta réponse.
Depuis ce matin dans plusieurs villes il y a des pénuries qui ne sont pas visibles sur la démo, mais bien sur le site du gouvernement, même en prenant en compte 1h de délais, ça semble pas matcher.
Apres c'est peut être juste la démo qui pose pb.

**Comment by Mael-Le-Garrec** [comment]
Tu as un example de station/carburant ?

**Comment by Emaison** [comment]
J'ai regardé sur : Station Service E. Leclerc Saint-Herblain et ce que je comprends c'est que c'est la même data sauf que sur la démo les indispos ne s'affichent pas (genre SP95 : indisponible"), la pop n'affiche que ce qui est disponible ce qui m'a prêté à confusion.

**Comment by Mael-Le-Garrec** [comment]
C'est ça, les données renvoyées ne précisent pas si le carburant est manquant ou il s'il n'est simplement jamais présent.

Je ne sais pas s'il est pertinent d'ajouter les carburants indisponibles, ça peut prêter à confusion en pensant qu'ils sont disponibles en temps normal.

**Comment by Emaison** [comment]
Je pense que c'est mieux comme  ça effectivement.
Merci pour tes retours !
